__author__ = 'mac'

team_dic = {}
team_dic["Atlanta Hawks"] = {"Playoff":"Yes", "Conference":"Eastern", "Wins":48}
team_dic["Boston Celtics"] = {"Playoff":"Yes", "Conference":"Eastern", "Wins":48}
team_dic["Brooklyn Nets"] = {"Playoff":"No", "Conference":"Eastern", "Wins":21}
team_dic["Charlotte Hornets"] = {"Playoff":"Yes", "Conference":"Eastern", "Wins":48}
team_dic["Chicago Bulls"] = {"Playoff":"No", "Conference":"Eastern", "Wins":42}
team_dic["Cleveland Cavaliers"] = {"Playoff":"Yes", "Conference":"Eastern", "Wins":57}
team_dic["Dallas Mavericks"] = {"Playoff":"Yes", "Conference":"Western", "Wins":42}
team_dic["Denver Nuggets"] = {"Playoff":"No", "Conference":"Western", "Wins":33}
team_dic["Detroit Pistons"] = {"Playoff":"Yes", "Conference":"Eastern", "Wins":44}
team_dic["Golden State Warriors"] = {"Playoff":"Yes", "Conference":"Western", "Wins":73}
team_dic["Houston Rockets"] = {"Playoff":"Yes", "Conference":"Western", "Wins":41}
team_dic["Indiana Pacers"] = {"Playoff":"Yes", "Conference":"Eastern", "Wins":45}
team_dic["Los Angeles Clippers"] = {"Playoff":"Yes", "Conference":"Western", "Wins":53}
team_dic["Los Angeles Lakers"] = {"Playoff":"No", "Conference":"Western", "Wins":17}
team_dic["Memphis Grizzlies"] = {"Playoff":"Yes", "Conference":"Western", "Wins":42}
team_dic["Miami Heat"] = {"Playoff":"Yes", "Conference":"Eastern", "Wins":48}
team_dic["Milwaukee Bucks"] = {"Playoff":"No", "Conference":"Eastern", "Wins":33}
team_dic["Minnesota Timberwolves"] = {"Playoff":"No", "Conference":"Western", "Wins":29}
team_dic["New Orleans Pelicans"] = {"Playoff":"No", "Conference":"Western", "Wins":30}
team_dic["New York Knicks"] = {"Playoff":"No", "Conference":"Eastern", "Wins":32}
team_dic["Oklahoma City Thunder"] = {"Playoff":"Yes", "Conference":"Western", "Wins":55}
team_dic["Orlando Magic"] = {"Playoff":"No", "Conference":"Eastern", "Wins":35}
team_dic["Philadelphia 76ers"] = {"Playoff":"No", "Conference":"Eastern", "Wins":10}
team_dic["Phoenix Suns"] = {"Playoff":"No", "Conference":"Western", "Wins":23}
team_dic["Portland Trail Blazers"] = {"Playoff":"Yes", "Conference":"Western", "Wins":44}
team_dic["Sacramento Kings"] = {"Playoff":"No", "Conference":"Western", "Wins":33}
team_dic["San Antonio Spurs"] = {"Playoff":"Yes", "Conference":"Western", "Wins":67}
team_dic["Toronto Raptors"] = {"Playoff":"Yes", "Conference":"Eastern", "Wins":56}
team_dic["Utah Jazz"] = {"Playoff":"No", "Conference":"Western", "Wins":40}
team_dic["Washington Wizards"] = {"Playoff":"No", "Conference":"Eastern", "Wins":41}
